// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/papi-hair-design/PapiLuxuryLanding.tsx": () => import("../components/mockups/papi-hair-design/PapiLuxuryLanding.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-CUqg3a/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-CUqg3a/Lp14.tsx"),
  "./components/mockups/templates/TerminalStyleSupportConsole-U6oiiS/App.tsx": () => import("../components/mockups/templates/TerminalStyleSupportConsole-U6oiiS/App.tsx")
};
